from fastapi import FastAPI
from backend.models import LoginRequest,CompletedCoursesRequest, ScheduleCheckRequest
from backend.auth import login_user
from backend.data_manager import (load_required_courses, load_semester_courses, get_completed_required_courses, get_elective_credits,save_completed_info)
from backend.planner import (add_course_groups,get_eligible_semester_courses,get_blocked_semester_courses,required_progress,check_schedule)
